/* TODO: Implement p, P, i, Esc */
/* Free keys: f, g, q, x */

user_pref("browser.autofocus", false);
user_pref("browser.fullscreen.animate", false);
user_pref("browser.tabs.animate", false);
user_pref("general.autoScroll", true);
user_pref("general.smoothScroll", false);
user_pref("general.warnOnAboutConfig", false);

user_pref("extensions.dorandoKeyConfig.main.focusURLBar", "][O][");
user_pref("extensions.dorandoKeyConfig.main.goBackKb", "][H][");
user_pref("extensions.dorandoKeyConfig.main.goForwardKb", "][L][");
user_pref("extensions.dorandoKeyConfig.main.key_close", "][D][");
user_pref("extensions.dorandoKeyConfig.main.key_find", "shift][/][");
user_pref("extensions.dorandoKeyConfig.main.key_findAgain", "][N][");
user_pref("extensions.dorandoKeyConfig.main.key_findPrevious", "shift][N][");
user_pref("extensions.dorandoKeyConfig.main.key_fullScreen", "][Z][");
user_pref("extensions.dorandoKeyConfig.main.key_fullZoomEnlarge", "shift][+][");
user_pref("extensions.dorandoKeyConfig.main.key_fullZoomReduce", "][-][");
user_pref("extensions.dorandoKeyConfig.main.key_fullZoomReset", "][=][");
user_pref("extensions.dorandoKeyConfig.main.key_keyconfig", "][C][");
user_pref("extensions.dorandoKeyConfig.main.key_newNavigator", "][W][");
user_pref("extensions.dorandoKeyConfig.main.key_newNavigatorTab", "][T][");
user_pref("extensions.dorandoKeyConfig.main.key_openAddons", "][A][");
user_pref("extensions.dorandoKeyConfig.main.key_openDownloads", "][V][");
user_pref("extensions.dorandoKeyConfig.main.key_privatebrowsing", "shift][W][");
user_pref("extensions.dorandoKeyConfig.main.key_search", "shift][O][");
user_pref("extensions.dorandoKeyConfig.main.key_selectLastTab", "][)][");
user_pref("extensions.dorandoKeyConfig.main.key_selectTab1", "][&][");
user_pref("extensions.dorandoKeyConfig.main.key_selectTab2", "][É][");
user_pref("extensions.dorandoKeyConfig.main.key_selectTab3", "][\"][");
user_pref("extensions.dorandoKeyConfig.main.key_stop", "][S][");
user_pref("extensions.dorandoKeyConfig.main.key_toggleMute", "][M][");
user_pref("extensions.dorandoKeyConfig.main.key_undoCloseTab", "][U][");
user_pref("extensions.dorandoKeyConfig.main.manBookmarkKb", "][B][");
user_pref("extensions.dorandoKeyConfig.main.tabGroups-key-tabView", "][E][");
user_pref("extensions.dorandoKeyConfig.main.xxx_key1_Copy URL", "][Y][][var ClipboardHelper = Components.classes[\"@mozilla.org/widget/clipboardhelper;1\"].getService(Components.interfaces.nsIClipboardHelper);\n\nClipboardHelper.copyString(content.location); ][chrome://browser/content/browser.xul");
user_pref("extensions.dorandoKeyConfig.main.xxx_key1_Scroll down", "][J][][goDoCommand('cmd_scrollLineDown');][chrome://browser/content/browser.xul");
user_pref("extensions.dorandoKeyConfig.main.xxx_key1_Scroll up", "][K][][goDoCommand('cmd_scrollLineUp');][chrome://browser/content/browser.xul");
user_pref("extensions.dorandoKeyConfig.main.xxx_key28_Browser:Reload", "][R][");
user_pref("extensions.dorandoKeyConfig.main.xxx_key30_Browser:ReloadSkipCache", "shift][R][");
user_pref("extensions.dorandoKeyConfig.main.xxx_key50_cmd_fullZoomEnlarge", "!][][");

user_pref("extensions.dorandoKeyConfig.main.focusChatBar", "!][][");
user_pref("extensions.dorandoKeyConfig.main.focusURLBar2", "!][][");
user_pref("extensions.dorandoKeyConfig.main.goBackKb2", "!][][");
user_pref("extensions.dorandoKeyConfig.main.goForwardKb2", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_browserConsole", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_browserToolbox", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_closeWindow", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_devToolbar", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_devToolboxMenuItem", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_devToolboxMenuItemF12", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_inspector", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_jsdebugger", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_netmonitor", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_performance", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_quitApplication", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_reload", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_responsiveUI", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_scratchpad", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_search2", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_selectTab6", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_selectTab7", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_selectTab8", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_showAllTabs", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_styleeditor", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_switchTextDirection", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_undoCloseWindow", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_viewInfo", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_webconsole", "!][][");
user_pref("extensions.dorandoKeyConfig.main.key_webide", "!][][");
user_pref("extensions.dorandoKeyConfig.main.openFileKb", "!][][");
user_pref("extensions.dorandoKeyConfig.main.showAllHistoryKb", "!][][");
user_pref("extensions.dorandoKeyConfig.main.web-developer-tools-3-key", "!][][");
user_pref("extensions.dorandoKeyConfig.main.xxx_key33_Browser:ReloadSkipCache", "!][][");
user_pref("extensions.dorandoKeyConfig.main.xxx_key39_cmd_findAgain", "!][][");
user_pref("extensions.dorandoKeyConfig.main.xxx_key40_cmd_findPrevious", "!][][");
user_pref("extensions.dorandoKeyConfig.main.xxx_key50_cmd_fullZoomEnlarge", "!][][");
