#!/usr/bin/perl -w

use strict;
use Convert::Color::HUSL;

my @colors = (
	[215,  34, 59],   # Black   Comments
	[ 11, 100, 59],   # Red     Error
	[126, 100, 59],   # Green   --
	[ 52, 100, 79],   # Gold    --
	[243, 100, 59],   # Blue    --
	[336, 100, 59],   # Magenta --
	[144, 100, 59],   # Cyan    --
	[  0,   0, 100],  # White   --
	[  0,   0, 16],   # Black   Cursorline
	[ 20, 100, 59],   # Orange  Todo
	[126, 100, 79],   # Green   Menus
	[ 52, 100, 79],   # Yellow  Keywords
	[243, 100, 79],   # Blue    String
	[272, 100, 59],   # Purple  PreProc
	[144, 100, 79],   # Cyan    --
	[  0,   0, 79],   # Gray    --
);

open my $xrdb, '|-', 'xrdb';

print $xrdb <DATA>;
printf $xrdb "*color%-4s#%02x%02x%02x\n", "$_:", map int(255.5 * $_),
	Convert::Color::HUSL->new(@{$colors[$_]})->rgb() for 0..15;

__DATA__

! Main settings
xterm*termName:   xterm-256color
*loginShell:      true
*cursorOffTime:   0
*bellIsUrgent:    true
*saveLines:       65535
*showBlinkAsBold: true
xterm*scrollBar:  false
*borderWidth:     0

XTerm.VT100.translations: #override \
Ctrl<Key>BackSpace: string("\033\010")

! Font
*faceName:     Hack
*faceSize:     11
Xft.antialias: 1
Xft.autohint:  1
Xft.hinting:   1
Xft.hintstyle: hintslight
Xft.rgba:      rgb

#if WIDTH > 1600
	*scaleHeight: 1.10
#else
	*scaleHeight: 1.00
#endif

xterm*foreground: #fefde7
xterm*background: #18181a

